myset = {1, 2, 3}
another_set = set([3, 4, 5, 2, 3, 4, 5, 5])
print("Set (removes duplicates from a list):", another_set)
myset.add(4)
myset.remove(2)
print("Updated set:", myset)
print("Checking for 3 in set:", 3 in myset)
print("Looping through set elements:")
for element in myset:
    print("Element:", element)
set_union = myset.union(another_set)
print("Union of sets:", set_union)
set_intersection = myset.intersection(another_set)
print("Intersection of sets:", set_intersection)
set_difference = myset.difference(another_set)
print("Difference of sets (myset - another_set):", set_difference)
print("Checking if myset is a subset of another_set:", myset.issubset(another_set))
copyset = myset.copy()
print("Copied set:", copyset)